
cmake_minimum_required(VERSION ${CMAKE_VERSION}) # this file comes with cmake

set(command "C:/msys64/ucrt64/bin/cmake.exe;-DCMAKE_C_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe;-DCMAKE_CXX_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe;-DCMAKE_AR=C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/lib.exe;-DBUILD_SHARED_LIBS=OFF;-DBUILD_STATIC_LIBS=ON;-DBUILD_TESTING=OFF;-DCMAKE_BUILD_TYPE=RELEASE;-DCMAKE_CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING;-DCMAKE_CXX_FLAGS_DEBUG=/Z7 /Ob0 /Od /RTC1 -MDd;-DCMAKE_CXX_FLAGS_MISIZEREL=/O1 /Ob1 /DNDEBUG -MD;-DCMAKE_CXX_FLAGS_RELEASE=/O2 /Ob2 /DNDEBUG -MD;-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=/Z7 /O2 /Ob1 /DNDEBUG -MD;-DCMAKE_CXX_STANDARD=17;-DCMAKE_C_FLAGS=/DWIN32 /D_WINDOWS;-DCMAKE_C_FLAGS_DEBUG=/Z7 /Ob0 /Od /RTC1 -MDd;-DCMAKE_C_FLAGS_MISIZEREL=/O1 /Ob1 /DNDEBUG -MD;-DCMAKE_C_FLAGS_RELEASE=/O2 /Ob2 /DNDEBUG -MD;-DCMAKE_C_FLAGS_RELWITHDEBINFO=/Z7 /O2 /Ob1 /DNDEBUG -MD;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=;-DCMAKE_INSTALL_LIBDIR=lib;-DCMAKE_OSX_SYSROOT=;-DCMAKE_VERBOSE_MAKEFILE=FALSE;-DCMAKE_INSTALL_PREFIX=C:/Users/nengj/OneDrive/Desktop/VSLAM/build_hybrid/arrow/src/arrow_cpp-build/xsimd_ep/src/xsimd_ep-install;-GNinja;-S;C:/Users/nengj/OneDrive/Desktop/VSLAM/build_hybrid/arrow/src/arrow_cpp-build/src/xsimd_ep;-B;C:/Users/nengj/OneDrive/Desktop/VSLAM/build_hybrid/arrow/src/arrow_cpp-build/src/xsimd_ep-build")
set(log_merged "")
set(log_output_on_failure "1")
set(stdout_log "C:/Users/nengj/OneDrive/Desktop/VSLAM/build_hybrid/arrow/src/arrow_cpp-build/src/xsimd_ep-stamp/xsimd_ep-configure-out.log")
set(stderr_log "C:/Users/nengj/OneDrive/Desktop/VSLAM/build_hybrid/arrow/src/arrow_cpp-build/src/xsimd_ep-stamp/xsimd_ep-configure-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
)
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  C:/Users/nengj/OneDrive/Desktop/VSLAM/build_hybrid/arrow/src/arrow_cpp-build/src/xsimd_ep-stamp/xsimd_ep-configure-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  if(NOT "Ninja" MATCHES "Ninja")
    set(msg "xsimd_ep configure command succeeded.  See also C:/Users/nengj/OneDrive/Desktop/VSLAM/build_hybrid/arrow/src/arrow_cpp-build/src/xsimd_ep-stamp/xsimd_ep-configure-*.log")
    message(STATUS "${msg}")
  endif()
endif()
